config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :events

  resources :users do
    resources :avatars, only: [:create]
  end

  root 'events#index'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  namespace :admin do
    resources :events
    resources :users
    root 'admin#index'
  end
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :admin, foreign_key: 'admin_id', class_name: 'User'
    has_many :attendances, dependent: :destroy
    has_many :users, through: :attendances

    validates :start_date, presence: true, if: :in_the_futur
    validates :duration,
        presence: true,
        numericality: {greater_than: 0 },
        if: :is_multiple_five?
    validates :title, 
        presence: true, 
        length: { in: 5..140 }
    validates :description, 
        presence: true,
        length: { in: 20..1000 }
    validates :price,
        presence: true,
        numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
    validates :location, presence: true

    def in_the_futur
        errors.add(:start_date, "You can't create an even in the past.") unless start_date > DateTime.now
    end
    
    def is_multiple_five?
    errors.add(:duration, "Must be a multiple of five!") unless duration % 5 == 0
    end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_admin_event, only: %i[ show edit update destroy ]

  # GET /admin/events or /admin/events.json
  def index
    @admin_events = Event.all
    @not_validated_events = Event.where(validated: nil)
  end

  # GET /admin/events/1 or /admin/events/1.json
  def show
  end

  # GET /admin/events/new
  def new
    @admin_event = Event.new
  end

  # GET /admin/events/1/edit
  def edit
  end

  # POST /admin/events or /admin/events.json
  def create
    @admin_event = Event.new(admin_event_params)

    respond_to do |format|
      if @admin_event.save
        format.html { redirect_to admin_event_url(@admin_event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @admin_event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/events/1 or /admin/events/1.json
  def update
    respond_to do |format|
      if @admin_event.update(admin_event_params)
        format.html { redirect_to admin_event_url(@admin_event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/events/1 or /admin/events/1.json
  def destroy
    @admin_event.destroy

    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_event
      @admin_event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_event_params
      params.fetch(:admin_event, {})
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.where(validated: true)
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(
            title: params[:title],
            description: params[:description],
            price: params[:price],
            admin: current_user,
            location: params[:location],
            start_date: params[:start_date],
            duration: params[:duration]
        )
  
        if @event.save
            redirect_to :root
        else 
            render :new
        end
    end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_event.html.erb
<div id="<%= dom_id event %>">
</div>

app/views/admin/events/_form.html.erb
<%= form_with url: admin_events_path, method: :post do |form| %>

  <div class="m-3 ">
      <label>Validé ?</label>
      <%= form.check_box :validated%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", admin_event: @admin_event %>

<br>

<div>
  <%= link_to "Show this event", @admin_event %> |
  <%= link_to "Back to events", admin_events_path %>
</div>

app/views/admin/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events</h1>

<div id="admin_events">
  <% @admin_events.each do |admin_event| %>
    <%= render admin_event %>
    <p>
      <%= admin_event.title %>
      <%= admin_event.validated %>
      <%= link_to "Show this event", admin_event_path(admin_event.id) %>
    </p>
  <% end %>
</div>

<h2>Validation</h2>

<div id="admin_events">
  <% @not_validated_events.each do |admin_event| %>
    <%= render admin_event %>
    <p>
      <%= admin_event.title %>
      <%= admin_event.validated %>
      <%= link_to "Show this event", admin_event_path(admin_event.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New event", new_admin_event_path %>

app/views/admin/events/new.html.erb
<h1>New event</h1>

<%= render "form", admin_event: @admin_event %>

<br>

<div>
  <%= link_to "Back to events", admin_events_path %>
</div>

app/views/admin/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_event %>

<div>
  <%= link_to "Edit this event", edit_admin_event_path(@admin_event) %> |
  <%= link_to "Back to events", admin_events_path %>

  <%= button_to "Destroy this event", @admin_event, method: :delete %>
</div>