config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :events

  resources :users do
    resources :avatars, only: [:create]
  end

  root 'events#index'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  namespace :admin do
    resources :events
    resources :users
    root 'admin#index'
  end
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :admin, foreign_key: 'admin_id', class_name: 'User'
    has_many :attendances, dependent: :destroy
    has_many :users, through: :attendances

    validates :start_date, presence: true, if: :in_the_futur
    validates :duration,
        presence: true,
        numericality: {greater_than: 0 },
        if: :is_multiple_five?
    validates :title, 
        presence: true, 
        length: { in: 5..140 }
    validates :description, 
        presence: true,
        length: { in: 20..1000 }
    validates :price,
        presence: true,
        numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
    validates :location, presence: true

    def in_the_futur
        errors.add(:start_date, "You can't create an even in the past.") unless start_date > DateTime.now
    end
    
    def is_multiple_five?
    errors.add(:duration, "Must be a multiple of five!") unless duration % 5 == 0
    end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_admin_event, only: %i[ show edit update destroy ]

  # GET /admin/events or /admin/events.json
  def index
    @admin_events = Event.all
    @not_validated_events = Event.where(validated: nil)
  end

  # GET /admin/events/1 or /admin/events/1.json
  def show
  end

  # GET /admin/events/new
  def new
    @admin_event = Event.new
  end

  # GET /admin/events/1/edit
  def edit
  end

  # POST /admin/events or /admin/events.json
  def create
    @admin_event = Event.new(admin_event_params)

    respond_to do |format|
      if @admin_event.save
        format.html { redirect_to admin_event_url(@admin_event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @admin_event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/events/1 or /admin/events/1.json
  def update
    respond_to do |format|
      if @admin_event.update(admin_event_params)
        format.html { redirect_to admin_event_url(@admin_event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/events/1 or /admin/events/1.json
  def destroy
    @admin_event.destroy

    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_event
      @admin_event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_event_params
      params.fetch(:admin_event, {})
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.where(validated: true)
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(
            title: params[:title],
            description: params[:description],
            price: params[:price],
            admin: current_user,
            location: params[:location],
            start_date: params[:start_date],
            duration: params[:duration]
        )
  
        if @event.save
            redirect_to :root
        else 
            render :new
        end
    end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="d-flex flex-wrap justify-content-center align-items-center">
    <% @events.reverse_each do |event| %>
    <div class="w-50 p-5 rounded-3 m-3 blur">
        <h2><%= event.title %></h2>
        <p><%= event.description %></p>
        <p><%= event.price %>€</p>
        <%= link_to "Voir plus" ,event_path(event.id), class: "btn btn-dark" %>
    </div>
    <% end %>
</div>

app/views/events/new.html.erb
<div class="d-flex justify-content-center align-items-center pt-5">
    <div class= "text-center blur p-4" style= "width : 500px">
        <h2>Crée un événement</h2>
        <%= form_with url: "/events", method: :post do |f| %>
            <div class="m-3 ">
                <label class= "pb-2">Titre</label>
                <%= f.text_field :title, class:'form-control bg-transparent border-dark'%>
            </div>
            <div class="m-3 ">
                <label class= "pb-2">Description</label>
                <%= f.text_area :description, class:'form-control bg-transparent border-dark', style: "height: 150px"%>
            </div>
            <div class="m-3 ">
                <label class= "pb-2">Prix</label>
                <%= f.number_field :price, in: 1..1000, class:'form-control bg-transparent border-dark'%>
            </div>
            <div class="m-3 ">
                <label class= "pb-2">Lieu</label>
                <%= f.text_field :location, class:'form-control bg-transparent border-dark'%>
            </div>
            <div class="m-3 ">
                <label class= "pb-2">Date</label>
                <%= f.date_field :start_date, class:'form-control bg-transparent border-dark'%>
            </div>
            <div class="m-3 ">
                <label class= "pb-2">Durée (en minute)</label>
                <%= f.number_field :duration, step: 5, class:'form-control bg-transparent border-dark'%>
            </div>
            <div class="">
                <button type="submit" class="btn btn-lg btn-primary mt-3">Poster</button>
            </div>
        <% end %>
    </div>
</div>

app/views/events/show.html.erb
<h3><%= @event.title %></h3>
<h3><%= @event.description %></h3>
<h3><%= @event.price %>€</h3>
<h3><%= @event.location %></h3>
<h3><%= @event.start_date %></h3>
<h3><%= @event.duration %> minutes</h3>
<h3><%= @event.admin.first_name %></h3>
<%= button_to "Passer commande", checkout_create_path(total: @event.price), class: "btn btn-primary", remote: true %>