config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :events

  resources :users do
    resources :avatars, only: [:create]
  end

  root 'events#index'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  namespace :admin do
    resources :events
    resources :users
    root 'admin#index'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send
    
    has_many :attendances, dependent: :destroy
    has_many :events, through: :attendances, dependent: :destroy
    has_many :administrated_events, foreign_key: 'admin_id', class_name: 'Event', dependent: :destroy
    has_one_attached :avatar, dependent: :destroy

    validates :email,
        presence: true,
        uniqueness: true
    validates :first_name, presence: true
    validates :last_name, presence: true

    def welcome_send
    UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_admin_user, only: %i[ show edit update destroy ]

  # GET /admin/users or /admin/users.json
  def index
    @users = User.all
  end

  # GET /admin/users/1 or /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users or /admin/users.json
  def create
    @admin_user = User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to admin_user_url(@admin_user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1 or /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to admin_user_url(@admin_user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1 or /admin/users/1.json
  def destroy
    @admin_user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_user_params
      params.fetch(:admin_user, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: admin_user) do |form| %>
  <% if admin_user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
        <% admin_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", admin_user: @admin_user %>

<br>

<div>
  <%= link_to "Show this user", @admin_user %> |
  <%= link_to "Back to users", admin_users_path %>
</div>

app/views/admin/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="admin_users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= user.first_name %>
      <%= link_to "Show this user", admin_user_path(user.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render "form", admin_user: @admin_user %>

<br>

<div>
  <%= link_to "Back to users", admin_users_path %>
</div>

app/views/admin/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin_user %>

<div>
  <ul>
    <li><%= @admin_user.first_name %></li>
    <li><%= @admin_user.last_name %></li>
    <li><%= @admin_user.email %></li>
  </ul>
  
  <%= link_to "Edit this user", edit_admin_user_path(@admin_user) %> |
  <%= link_to "Back to users", admin_users_path %>

  <%= button_to "Destroy this user", admin_user_path(@admin_user.id), method: :delete %>
</div>