config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :events

  resources :users do
    resources :avatars, only: [:create]
  end

  root 'events#index'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  namespace :admin do
    resources :events
    resources :users
    root 'admin#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :admin, foreign_key: 'admin_id', class_name: 'User'
    has_many :attendances, dependent: :destroy
    has_many :users, through: :attendances

    validates :start_date, presence: true, if: :in_the_futur
    validates :duration,
        presence: true,
        numericality: {greater_than: 0 },
        if: :is_multiple_five?
    validates :title, 
        presence: true, 
        length: { in: 5..140 }
    validates :description, 
        presence: true,
        length: { in: 20..1000 }
    validates :price,
        presence: true,
        numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
    validates :location, presence: true

    def in_the_futur
        errors.add(:start_date, "You can't create an even in the past.") unless start_date > DateTime.now
    end
    
    def is_multiple_five?
    errors.add(:duration, "Must be a multiple of five!") unless duration % 5 == 0
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send
    
    has_many :attendances, dependent: :destroy
    has_many :events, through: :attendances, dependent: :destroy
    has_many :administrated_events, foreign_key: 'admin_id', class_name: 'Event', dependent: :destroy
    has_one_attached :avatar, dependent: :destroy

    validates :email,
        presence: true,
        uniqueness: true
    validates :first_name, presence: true
    validates :last_name, presence: true

    def welcome_send
    UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
    before_action :is_admin?

    def index
        @users = User.all
        @events = Event.all
    end

    private

    def is_admin?
        unless current_user.is_admin == true
          flash[:danger] = "Accès refusé. Vous n'êtes pas administrateur de ce site."
          redirect_to root_path
        end
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?

    def configure_devise_parameters
        devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
        devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
    end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
    def create
        @user = User.find(params[:user_id])
        @user.avatar.attach(params[:avatar])
        redirect_to(user_path(@user))
    end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    @total = params[:total].to_d
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        },
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end

  def cancel
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.where(validated: true)
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(
            title: params[:title],
            description: params[:description],
            price: params[:price],
            admin: current_user,
            location: params[:location],
            start_date: params[:start_date],
            duration: params[:duration]
        )
  
        if @event.save
            redirect_to :root
        else 
            render :new
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admin/index.html.erb
<%= link_to "Show user dashboard", admin_users_path, class: "btn btn-primary" %>
<%= link_to "Show event dashboard", admin_events_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application"%>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body class= "gradient-bg">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <header class="p-3 text-bg-dark sticky-top">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><%= link_to "Eventbrite" , :root, class: "fs-2 fw-bold text-white text-decoration-none" %></li>
          </ul>
          
          <div class="text-end d-flex">
              <% if user_signed_in? %>
              <%= link_to "Crée un évenement", new_event_path, class: "btn btn-outline-light me-2" %>
              <div class="dropdown">
              <button class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Ton compte</button>
                <ul class="dropdown-menu">
                  <li><%= link_to "Mon compte", user_path(current_user.id), class: "dropdown-item" %></li>
                  <% if current_user.is_admin == true %>
                    <li><%= link_to "Dashboard", admin_root_path, class: "dropdown-item" %></li>
                  <% end %>
                  <li><%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %></li>
                  <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item text-danger" %></li>
                </ul>
              </div>
              <% else %>  
                <%= link_to "Sign in", new_user_session_path, class: "btn btn-outline-light me-2"%>
                <%= link_to "Sign up", new_user_registration_path, class: "btn btn-light" %>
              <% end %>
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>